@Echo off
title Building...
echo Building...
python -m PyInstaller --icon=app_icon.ico --onefile Cypher77.py 

title Copying...
echo Copying Files...

echo Copying Variables...
copy variables.txt dist\variables.txt

echo Copying Splashes...
copy splashes.txt dist\splashes.txt

echo Copying Modules...
xcopy ciphers dist\ciphers /E /I /EXCLUDE:buildexclude.txt

pause